-- MySQL Script generated by MySQL Workbench
-- Fri Sep 21 21:16:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bonanza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bonanza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bonanza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `bonanza` ;

-- -----------------------------------------------------
-- Table `bonanza`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`user` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userPhoneNum` VARCHAR(11) NOT NULL,
  `userDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userPassword` CHAR(32) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userGender` ENUM('Male', 'Female') NOT NULL,
  `userPic` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userPhoneNum_UNIQUE` (`userPhoneNum` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`team` (
  `teamId` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(45) NOT NULL,
  `teamDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `teamIntro` TEXT NOT NULL,
  `teamPic` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`teamId`),
  UNIQUE INDEX `teamName_UNIQUE` (`teamName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`project` (
  `projectId` INT NOT NULL AUTO_INCREMENT,
  `projectDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `projectName` VARCHAR(45) NOT NULL,
  `projectState` ENUM('Unfinish', 'Finish', 'OverTime') NOT NULL,
  `projectStartTime` DATETIME NOT NULL,
  `projectFinishTime` DATETIME NOT NULL,
  `team_teamId` INT NOT NULL,
  PRIMARY KEY (`projectId`),
  INDEX `fk_project_team1_idx` (`team_teamId` ASC),
  CONSTRAINT `fk_project_team1`
    FOREIGN KEY (`team_teamId`)
    REFERENCES `bonanza`.`team` (`teamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`comment` (
  `commentId` INT NOT NULL AUTO_INCREMENT,
  `commentDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `commentText` TEXT NOT NULL,
  `commentReplyTo` INT NULL DEFAULT NULL,
  `user_userId` INT NOT NULL,
  `project_projectId` INT NOT NULL,
  PRIMARY KEY (`commentId`),
  INDEX `fk_comment_user1_idx` (`user_userId` ASC),
  INDEX `fk_comment_project1_idx` (`project_projectId` ASC),
  INDEX `fk_comment_comment1_idx` (`commentReplyTo` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `bonanza`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_project1`
    FOREIGN KEY (`project_projectId`)
    REFERENCES `bonanza`.`project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_comment1`
    FOREIGN KEY (`commentReplyTo`)
    REFERENCES `bonanza`.`comment` (`commentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`plan` (
  `planId` INT NOT NULL AUTO_INCREMENT,
  `planDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `planName` VARCHAR(45) NOT NULL,
  `planIntro` TEXT NOT NULL,
  `planStartTime` DATETIME NOT NULL,
  `planFinishTime` DATETIME NOT NULL,
  `project_projectId` INT NOT NULL,
  PRIMARY KEY (`planId`),
  INDEX `fk_plan_project1_idx` (`project_projectId` ASC),
  CONSTRAINT `fk_plan_project1`
    FOREIGN KEY (`project_projectId`)
    REFERENCES `bonanza`.`project` (`projectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`task` (
  `taskId` INT NOT NULL AUTO_INCREMENT,
  `taskDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `taskName` VARCHAR(45) NOT NULL,
  `taskState` ENUM('Unfinish', 'Finish', 'OverTime') NOT NULL,
  `taskIntro` TEXT NOT NULL,
  `plan_planId` INT NOT NULL,
  PRIMARY KEY (`taskId`),
  INDEX `fk_task_plan1_idx` (`plan_planId` ASC),
  CONSTRAINT `fk_task_plan1`
    FOREIGN KEY (`plan_planId`)
    REFERENCES `bonanza`.`plan` (`planId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`team_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`team_has_user` (
  `team_teamId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  `userRole` ENUM('Creator', 'Admin', 'Member') NOT NULL,
  PRIMARY KEY (`team_teamId`, `user_userId`),
  INDEX `fk_team_has_user_user1_idx` (`user_userId` ASC),
  INDEX `fk_team_has_user_team_idx` (`team_teamId` ASC),
  CONSTRAINT `fk_team_has_user_team`
    FOREIGN KEY (`team_teamId`)
    REFERENCES `bonanza`.`team` (`teamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_team_has_user_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `bonanza`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`task_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`task_has_user` (
  `task_taskId` INT NOT NULL,
  `user_userId` INT NOT NULL,
  PRIMARY KEY (`task_taskId`, `user_userId`),
  INDEX `fk_task_has_user_user1_idx` (`user_userId` ASC),
  INDEX `fk_task_has_user_task1_idx` (`task_taskId` ASC),
  CONSTRAINT `fk_task_has_user_task1`
    FOREIGN KEY (`task_taskId`)
    REFERENCES `bonanza`.`task` (`taskId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_has_user_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `bonanza`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bonanza`.`photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bonanza`.`photo` (
  `photoId` INT NOT NULL AUTO_INCREMENT,
  `photoPic` LONGBLOB NOT NULL,
  `team_teamId` INT NOT NULL,
  PRIMARY KEY (`photoId`),
  INDEX `fk_photo_team1_idx` (`team_teamId` ASC),
  CONSTRAINT `fk_photo_team1`
    FOREIGN KEY (`team_teamId`)
    REFERENCES `bonanza`.`team` (`teamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
